version: "3"
services:
  rick-morty-app:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/app/src:z
      - ./public:/usr/app/public:z
    tty: true # docker run -t
    stdin_open: true # docker run -i

