const mockEpisodeData = [
  {
    id: 2,
    name: "Lawnmower Dog",
    air_date: "December 9, 2013",
    episode: "S01E02",
    characters: [
      "https://rickandmortyapi.com/api/character/1",
      "https://rickandmortyapi.com/api/character/2",
      "https://rickandmortyapi.com/api/character/38",
      "https://rickandmortyapi.com/api/character/46",
      "https://rickandmortyapi.com/api/character/63",
      "https://rickandmortyapi.com/api/character/80",
      "https://rickandmortyapi.com/api/character/175",
      "https://rickandmortyapi.com/api/character/221",
      "https://rickandmortyapi.com/api/character/239",
      "https://rickandmortyapi.com/api/character/246",
      "https://rickandmortyapi.com/api/character/304",
      "https://rickandmortyapi.com/api/character/305",
      "https://rickandmortyapi.com/api/character/306",
      "https://rickandmortyapi.com/api/character/329",
      "https://rickandmortyapi.com/api/character/338",
      "https://rickandmortyapi.com/api/character/396",
      "https://rickandmortyapi.com/api/character/397",
      "https://rickandmortyapi.com/api/character/398",
      "https://rickandmortyapi.com/api/character/405",
    ],
    url: "https://rickandmortyapi.com/api/episode/2",
    created: "2017-11-10T12:56:33.916Z",
  },
  {
    id: 11,
    name: "Ricksy Business",
    air_date: "April 14, 2014",
    episode: "S01E11",
    characters: [
      "https://rickandmortyapi.com/api/character/1",
      "https://rickandmortyapi.com/api/character/2",
      "https://rickandmortyapi.com/api/character/3",
      "https://rickandmortyapi.com/api/character/4",
      "https://rickandmortyapi.com/api/character/5",
      "https://rickandmortyapi.com/api/character/7",
      "https://rickandmortyapi.com/api/character/35",
      "https://rickandmortyapi.com/api/character/47",
      "https://rickandmortyapi.com/api/character/58",
      "https://rickandmortyapi.com/api/character/88",
      "https://rickandmortyapi.com/api/character/180",
      "https://rickandmortyapi.com/api/character/181",
      "https://rickandmortyapi.com/api/character/210",
      "https://rickandmortyapi.com/api/character/216",
      "https://rickandmortyapi.com/api/character/251",
      "https://rickandmortyapi.com/api/character/282",
      "https://rickandmortyapi.com/api/character/295",
      "https://rickandmortyapi.com/api/character/308",
      "https://rickandmortyapi.com/api/character/326",
      "https://rickandmortyapi.com/api/character/327",
      "https://rickandmortyapi.com/api/character/331",
      "https://rickandmortyapi.com/api/character/333",
      "https://rickandmortyapi.com/api/character/344",
      "https://rickandmortyapi.com/api/character/362",
      "https://rickandmortyapi.com/api/character/389",
      "https://rickandmortyapi.com/api/character/395",
      "https://rickandmortyapi.com/api/character/405",
      "https://rickandmortyapi.com/api/character/423",
      "https://rickandmortyapi.com/api/character/435",
      "https://rickandmortyapi.com/api/character/436",
    ],
    url: "https://rickandmortyapi.com/api/episode/11",
    created: "2017-11-10T12:56:34.850Z",
  },
  {
    id: 14,
    name: "Auto Erotic Assimilation",
    air_date: "August 9, 2015",
    episode: "S02E03",
    characters: [
      "https://rickandmortyapi.com/api/character/1",
      "https://rickandmortyapi.com/api/character/2",
      "https://rickandmortyapi.com/api/character/3",
      "https://rickandmortyapi.com/api/character/4",
      "https://rickandmortyapi.com/api/character/5",
      "https://rickandmortyapi.com/api/character/36",
      "https://rickandmortyapi.com/api/character/50",
      "https://rickandmortyapi.com/api/character/90",
      "https://rickandmortyapi.com/api/character/188",
      "https://rickandmortyapi.com/api/character/249",
      "https://rickandmortyapi.com/api/character/301",
      "https://rickandmortyapi.com/api/character/336",
      "https://rickandmortyapi.com/api/character/355",
      "https://rickandmortyapi.com/api/character/372",
    ],
    url: "https://rickandmortyapi.com/api/episode/14",
    created: "2017-11-10T12:56:35.158Z",
  },
];
